# Generated by Django 2.0.6 on 2018-06-29 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_relation_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='form_user',
            new_name='from_user',
        ),
    ]
