# Generated by Django 2.0.6 on 2018-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180629_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='to_relations_users',
            new_name='to_relation_users',
        ),
        migrations.AlterField(
            model_name='relation',
            name='relation_type',
            field=models.CharField(choices=[('f', 'Follow'), ('b', 'Block')], max_length=1),
        ),
    ]
