# Generated by Django 2.0.6 on 2018-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='post',
            name='user_photo',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
